name: Deploy using AWS SSM Send-Command

on:
  push:
    branches: [master]

jobs:
  start:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - name: AWS SSM Send-Command
        uses: peterkimzz/aws-ssm-send-command@master
        id: ssm
        with:
          aws-region: eu-central-1a
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          instance-ids: ${{ secrets.INSTANCE_ID }}

          working-directory: /home/ubuntu/apps/pern-web
          command: /bin/sh ./deploy.sh
